# Generated by Django 4.1.2 on 2023-02-11 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=150)),
                ('frete', models.CharField(choices=[('pagar', 'Pagar'), ('nao_pagar', 'Frete gratis')], max_length=150)),
                ('total_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date_of_purchase', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
