# Generated by Django 4.1.2 on 2023-02-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='products',
            field=models.ManyToManyField(related_name='name_product', to='products.products'),
        ),
    ]
