# Generated by Django 4.1.2 on 2023-02-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=150)),
                ('score', models.IntegerField()),
                ('image', models.ImageField(upload_to='Image/')),
            ],
        ),
    ]
